import img1 from "../../../assets/slider1.jpg";

export const productSuggestions = [
  {
    id: 1,
    title: "لپ تاپ فوق باریک ایسوس مدل VivoBook 15",
    description: "پردازنده اینتل سلرون، 8 گیگابایت رم، ۵۱۲ گیگابایت SSD",
    rating: 4.5,
    reviews: 42,
    oldPrice: "۸۸,۰۰۰,۰۰۰",
    newPrice: "۷۷,۰۰۰,۰۰۰",
    discount: "30% تخفیف",
    timeLeft: "فقط ۲ روز تا پایان تخفیف!",
    sold: 17,
    total: 81,
    image: img1,
    isFavorite: false,
  },
  {
    id: 2,
    title: "لپ تاپ فوق باریک ایسوس مدل VivoBook 15",
    description: "پردازنده اینتل سلرون، 8 گیگابایت رم، ۵۱۲ گیگابایت SSD",
    rating: 4.5,
    reviews: 42,
    oldPrice: "۸۸,۰۰۰,۰۰۰",
    newPrice: "۷۷,۰۰۰,۰۰۰",
    discount: "30% تخفیف",
    timeLeft: "فقط ۲ روز تا پایان تخفیف!",
    sold: 17,
    total: 81,
    image: img1,
    isFavorite: false,
  },
  {
    id: 3,
    title: "لپ تاپ فوق باریک ایسوس مدل VivoBook 15",
    description: "پردازنده اینتل سلرون، 8 گیگابایت رم، ۵۱۲ گیگابایت SSD",
    rating: 4.5,
    reviews: 42,
    oldPrice: "۸۸,۰۰۰,۰۰۰",
    newPrice: "۷۷,۰۰۰,۰۰۰",
    discount: "30% تخفیف",
    timeLeft: "فقط ۲ روز تا پایان تخفیف!",
    sold: 17,
    total: 81,
    image: img1,
    isFavorite: false,
  },
  {
    id: 4,
    title: "لپ تاپ فوق باریک ایسوس مدل VivoBook 15",
    description: "پردازنده اینتل سلرون، 8 گیگابایت رم، ۵۱۲ گیگابایت SSD",
    rating: 4.5,
    reviews: 42,
    oldPrice: "۸۸,۰۰۰,۰۰۰",
    newPrice: "۷۷,۰۰۰,۰۰۰",
    discount: "30% تخفیف",
    timeLeft: "فقط ۲ روز تا پایان تخفیف!",
    sold: 17,
    total: 81,
    image: img1,
    isFavorite: false,
  },
];
